package com.zakatfitrah.entity;
// Generated May 18, 2019 12:34:27 PM by Hibernate Tools 4.3.1



/**
 * Pendataan generated by hbm2java
 */
public class Pendataan  implements java.io.Serializable {


     private Integer no;
     private String namaKk;
     private String jenisZakat;
     private String jumlahAnggota;
     private String beras;
     private String uang;
     private String keterangan;

    public Pendataan() {
    }

    public Pendataan(String namaKk, String jenisZakat, String jumlahAnggota, String beras, String uang, String keterangan) {
       this.namaKk = namaKk;
       this.jenisZakat = jenisZakat;
       this.jumlahAnggota = jumlahAnggota;
       this.beras = beras;
       this.uang = uang;
       this.keterangan = keterangan;
    }
   
    public Integer getNo() {
        return this.no;
    }
    
    public void setNo(Integer no) {
        this.no = no;
    }
    public String getNamaKk() {
        return this.namaKk;
    }
    
    public void setNamaKk(String namaKk) {
        this.namaKk = namaKk;
    }
    public String getJenisZakat() {
        return this.jenisZakat;
    }
    
    public void setJenisZakat(String jenisZakat) {
        this.jenisZakat = jenisZakat;
    }
    public String getJumlahAnggota() {
        return this.jumlahAnggota;
    }
    
    public void setJumlahAnggota(String jumlahAnggota) {
        this.jumlahAnggota = jumlahAnggota;
    }
    public String getBeras() {
        return this.beras;
    }
    
    public void setBeras(String beras) {
        this.beras = beras;
    }
    public String getUang() {
        return this.uang;
    }
    
    public void setUang(String uang) {
        this.uang = uang;
    }
    public String getKeterangan() {
        return this.keterangan;
    }
    
    public void setKeterangan(String keterangan) {
        this.keterangan = keterangan;
    }




}


